/********************************************************************
* DaqFileCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DaqFileCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDaqFileCint();
extern void G__cpp_setup_inheritanceDaqFileCint();
extern void G__cpp_setup_typetableDaqFileCint();
extern void G__cpp_setup_memvarDaqFileCint();
extern void G__cpp_setup_globalDaqFileCint();
extern void G__cpp_setup_memfuncDaqFileCint();
extern void G__cpp_setup_funcDaqFileCint();
extern void G__set_cpp_environmentDaqFileCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DaqFile.hh"
#include "DaqFile-TypeDef.hh"
#include "Integral.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DaqFileCintLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__DaqFileCintLN_string;
extern G__linked_taginfo G__DaqFileCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DaqFileCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DaqFileCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DaqFileCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DaqFileCintLN_DaqFile;
extern G__linked_taginfo G__DaqFileCintLN_Integral;

/* STUB derived class for protected member access */
